#####################################################################
# This is Jekyll's configuration file for this project.
#
# For more information, see the documentation:
#
#     https://jekyllrb.com/docs/configuration/
#####################################################################

# Site settings
title: The Footlight

# Project-specific settings.
# Needs https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/#keeping-your-site-up-to-date-with-the-github-pages-gem

# Build settings
markdown: kramdown

exclude: [vendor]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

iCalendar:
    defaults:
        tzid: "America/New_York"
        location: "465 Seneca Avenue, Ridgewood, Queens, NY 11385, United States"
        status: "CONFIRMED"
