#####################################################################
# This is Jekyll's configuration file for this project.
#
# For more information, see the documentation:
#
#     https://jekyllrb.com/docs/configuration/
#####################################################################

# Site settings
title: The Footlight

# Project-specific settings.
# Needs https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/#keeping-your-site-up-to-date-with-the-github-pages-gem

# Build settings
markdown: kramdown

exclude: [vendor]

paginate: 5
paginate_path: "/blog/page/:num/"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "calendars/*.ics"
    values:
      layout: "iCalendar"

iCalendar:
    defaults:
        tzid: "America/New_York"
        location: "465 Seneca Avenue, Ridgewood, Queens, NY 11385, United States"
        status: "CONFIRMED"
    date_format: "%B %e, %Y"
    time_format: "%l:%M %p"
    rrule_count_max_when_hourly_missing: 672
    rrule_count_max_when_daily_missing:  90
    rrule_count_max_when_weekly_missing: 8
